"""Create product table

Revision ID: 81006cf84bf3
Revises:
Create Date: 2026-03-22 11:50:32.029729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "81006cf84bf3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column(
            "name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
    )
    # ### end Alembic commands ###
