"""add column unit_price to order_product assosiation table

Revision ID: 7c4fa3653e5a
Revises: ab2c4f79274e
Create Date: 2026-03-22 21:04:15.445994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c4fa3653e5a"
down_revision: Union[str, Sequence[str], None] = "ab2c4f79274e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column(
            "unit_price", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "unit_price")
    # ### end Alembic commands ###
