"""add count column to order_product assosiation table

Revision ID: ab2c4f79274e
Revises: 83f28854c71d
Create Date: 2026-03-22 20:33:34.770392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ab2c4f79274e"
down_revision: Union[str, Sequence[str], None] = "83f28854c71d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association_table",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association_table", "count")
    # ### end Alembic commands ###
